[[redirects]]
from = "/cdi-ii/0001-transicao-para-dim-sup-1.html"
to = "/cdi-ii/transicao-para-dim-sup-1"

[[redirects]]
from = "/cdi-ii/0002-norma-topologia.html"
to = "/cdi-ii/norma-topologia"

[[redirects]]
from = "/cdi-ii/0003-funcoes-continuidade.html"
to = "/cdi-ii/funcoes-continuidade"

[[redirects]]
from = "/cdi-ii/0004-diferenciabilidade.html"
to = "/cdi-ii/diferenciabilidade"

[[redirects]]
from = "/cdi-ii/0005-derivada-composta.html"
to = "/cdi-ii/derivada-composta"

[[redirects]]
from = "/cdi-ii/0006-conjunto-de-nivel.html"
to = "/cdi-ii/conjunto-de-nivel"

[[redirects]]
from = "/cdi-ii/0007-derivada-ordem-superior.html"
to = "/cdi-ii/derivada-de-ordem-superior"

[[redirects]]
from = "/cdi-ii/0008-integracao.html"
to = "/cdi-ii/integracao"

[[redirects]]
from = "/cdi-ii/0009-integracao-funcoes.html"
to = "/cdi-ii/integracao-funcoes"

[[redirects]]
from = "/cdi-ii/0010-integracao-mudanca-var.html"
to = "/cdi-ii/integracao-mudanca-var"

[[redirects]]
from = "/cdi-ii/0011-aplicacoes-integral.html"
to = "/cdi-ii/aplicacoes-integral"

[[redirects]]
from = "/cdi-ii/0012-teorema-leibniz.html"
to = "/cdi-ii/teorema-leibniz"

[[redirects]]
from = "/cdi-ii/0013-funcao-inversa.html"
to = "/cdi-ii/funcao-inversa"

[[redirects]]
from = "/cdi-ii/0014-variedades.html"
to = "/cdi-ii/variedades"

[[redirects]]
from = "/cdi-ii/0015-extremos-condicionados.html"
to = "/cdi-ii/extremos-condicionados"

[[redirects]]
from = "/cdi-ii/0016-campos-vetoriais.html"
to = "/cdi-ii/campos-vetoriais"

[[redirects]]
from = "/cdi-ii/0017-green-fluxo-divergencia.html"
to = "/cdi-ii/teorema-de-green"

[[redirects]]
from = "/cdi-ii/0018-fluxo-divergencia.html"
to = "/cdi-ii/fluxo-teorema-divergencia"

[[redirects]]
from = "/cdi-ii/0019-rotacional-stokes.html"
to = "/cdi-ii/rotacional-teorema-stokes"

[[redirects]]
from = "/cdi-ii/exercicios/fichas-aulas-praticas.html"
to = "/cdi-ii/exercicios/fichas-aulas-praticas"

[[redirects]]
from = "/md/0001-perturbacoes.html"
to = "/md/perturbacoes"

[[redirects]]
from = "/md/0002-introducao-calculo-finito.html"
to = "/md/introducao-calculo-finito"

[[redirects]]
from = "/md/0003-formulas-fechadas-somatorios.html"
to = "/md/formulas-fechadas-somatorios"

[[redirects]]
from = "/md/0004-serie-harmonica.html"
to = "/md/serie-harmonica"

[[redirects]]
from = "/md/0005-inducao-matematica.html"
to = "/md/inducao-matematica"

[[redirects]]
from = "/md/0006-formula-de-abel.html"
to = "/md/formula-de-abel"

[[redirects]]
from = "/md/0007-funcoesgeradoras.html"
to = "/md/funcoes-geradoras"

[[redirects]]
from = "/md/0008-teonewton.html"
to = "/md/teorema-de-newton"

[[redirects]]
from = "/md/0009-combinatorio.html"
to = "/md/calculo-combinatorio"

[[redirects]]
from = "/md/0010-diffinitas.html"
to = "/md/equacoes-diferencas-finitas"

[[redirects]]
from = "/md/0011-FFT.html"
to = "/md/fft"

[[redirects]]
from = "/md/0012-MDC.html"
to = "/md/mdc-eq-diofantinas"

[[redirects]]
from = "/md/0013-calendario.html"
to = "/md/calendario"

[[redirects]]
from = "/md/0014-pascoa.html"
to = "/md/pascoa"

[[redirects]]
from = "/md/0015-congruencias.html"
to = "/md/congruencias"

[[redirects]]
from = "/md/0016-chines-restos.html"
to = "/md/teorema-chines-restos"

[[redirects]]
from = "/md/0017-rsa.html"
to = "/md/rsa"

[[redirects]]
from = "/md/0018-grafos-def.html"
to = "/md/grafos"

[[redirects]]
from = "/md/0019-pombal.html"
to = "/md/principio-pombal"

[[redirects]]
from = "/md/0020-labirintos.html"
to = "/md/labirintos"

[[redirects]]
from = "/md/0021-galeshapley.html"
to = "/md/relacionamentos-gale-shapley"

[[redirects]]
from = "/md/0022-kruskraldijkrsta.html"
to = "/md/kruskal-dijkstra"

[[redirects]]
from = "/md/0023-teoriadofluxo.html"
to = "/md/teoria-fluxo"

[[redirects]]
from = "/md/0024-grafoplanares.html"
to = "/md/grafos-planares"

[[redirects]]
from = "/md/0025-teoremakuratowski.html"
to = "/md/algoritmo-kuratowski"

[[redirects]]
from = "/md/0026-automatos.html"
to = "/md/automatos-finitos"

[[redirects]]
from = "/md/exercicios/fichas-aulas-praticas.html"
to = "/md/exercicios/fichas-aulas-praticas"

[[redirects]]
from = "/md/1001-calc-finito.html"
to = "/md/cheatsheet/calculo-finito"

[[redirects]]
from = "/md/1002-geradoras-sheet.html"
to = "/md/cheatsheet/funcoes-geradoras"

[[redirects]]
from = "/md/1003-calendarios.html"
to = "/md/cheatsheet/calendarios"

[[redirects]]
from = "/md/1004-mdc-cheat.html"
to = "/md/cheatsheet/mdc-equacoes-diofantinas"

[[redirects]]
from = "/md/1005-rsa-sheet.html"
to = "/md/cheatsheet/rsa"

[[redirects]]
from = "/md/1006-grafos.html"
to = "/md/cheatsheet/grafos"

[[redirects]]
from = "/md/tools/bezout-calculator.html"
to = "/md/tools/mdc-bezout-calculator"

[[redirects]]
from = "/md/tools/fft-calculator.html"
to = "/md/tools/fft-calculator"

[[redirects]]
from = "/md/tools/calendar-calculator.html"
to = "/md/tools/calendar-calculator"

[[redirects]]
from = "/md/tools/rsa-calculator.html"
to = "/md/tools/rsa-calculator"

[[redirects]]
from = "/md/tools/tcr-table-calculator.html"
to = "/md/tools/teorema-chines-restos-table-calculator"

[[redirects]]
from = "/lp/0001-conceitos-gerais.html"
to = "/lp/conceitos-gerais"

[[redirects]]
from = "/lp/0002-logica-proposicional-int.html"
to = "/lp/logica-proposicional-int"

[[redirects]]
from = "/lp/0003-logica-proposicional-sc.html"
to = "/lp/logica-proposicional-sc"

[[redirects]]
from = "/lp/0004-logica-primeiraordem-int.html"
to = "/lp/logica-primeira-ordem-int"

[[redirects]]
from = "/lp/0005-logica-primeiraordem-sc.html"
to = "/lp/logica-primeira-ordem-sc"

[[redirects]]
from = "/lp/0006-prog-logica.html"
to = "/lp/fundamentos-programacao-logica"

[[redirects]]
from = "/lp/0007-prolog-intro.html"
to = "/lp/prolog-intro"

[[redirects]]
from = "/lp/0008-prolog-mid.html"
to = "/lp/prolog-mid"

[[redirects]]
from = "/lp/0009-prolog-corte-neg.html"
to = "/lp/prolog-corte-neg"

[[redirects]]
from = "/lp/0010-prolog-lp.html"
to = "/lp/prolog-linguagem-programacao"

[[redirects]]
from = "/lp/0011-logica-proposicional-semantico.html"
to = "/lp/logica-proposicional-semantico"

[[redirects]]
from = "/lp/0012-lp-ii-bdds.html"
to = "/lp/logica-proposicional-ii-bdds"

[[redirects]]
from = "/lp/0013-algs-sat.html"
to = "/lp/algoritmos-sat"

[[redirects]]
from = "/lp/0014-lpo-semantico.html"
to = "/lp/logica-primeira-ordem-semantico"

[[redirects]]
from = "/lp/exercicios/fichas-aulas-praticas.html"
to = "/lp/exercicios/fichas-aulas-praticas"

[[redirects]]
from = "/lp/1000-faq.html"
to = "/lp/projeto/faq"

[[redirects]]
from = "/iaed/0001-introducao-programacao-c.html"
to = "/iaed/introducao-programacao-c"

[[redirects]]
from = "/iaed/0002-estruturas-controlo.html"
to = "/iaed/estruturas-controlo"

[[redirects]]
from = "/iaed/0003-input-output.html"
to = "/iaed/input-output"

[[redirects]]
from = "/iaed/0004-tabelas.html"
to = "/iaed/tabelas"

[[redirects]]
from = "/iaed/0005-ficheiros.html"
to = "/iaed/funcoes"

[[redirects]]
from = "/iaed/0006-estruturas.html"
to = "/iaed/estruturas"

[[redirects]]
from = "/iaed/0007-1elementos.html"
to = "/iaed/elementos-linguagem"

[[redirects]]
from = "/iaed/0007-2control.html"
to = "/iaed/controlo-execucao"

[[redirects]]
from = "/iaed/0008-intro_algoritmos.html"
to = "/iaed/introducao-algoritmos"

[[redirects]]
from = "/iaed/0009-algo_ord.html"
to = "/iaed/algoritmos-elementares-ordenacao"

[[redirects]]
from = "/iaed/0010-more_algo.html"
to = "/iaed/algoritmos-eficientes-ordenacao"

[[redirects]]
from = "/iaed/0011-even_more_algo.html"
to = "/iaed/algoritmos-elementares-ordenacao-2"

[[redirects]]
from = "/iaed/0012-ponteiros.html"
to = "/iaed/ponteiros"

[[redirects]]
from = "/iaed/0013-mem.html"
to = "/iaed/alocacao-dinamica-memoria"

[[redirects]]
from = "/iaed/0014-listas.html"
to = "/iaed/listas"

[[redirects]]
from = "/iaed/0015-tad.html"
to = "/iaed/tad"

[[redirects]]
from = "/iaed/0016-disp.html"
to = "/iaed/hash-tables"

[[redirects]]
from = "/iaed/0017-arv.html"
to = "/iaed/arvores-binarias"

[[redirects]]
from = "/iaed/0018-grafos.html"
to = "/iaed/grafos"

[[redirects]]
from = "/iaed/1000-algoritmos.sheet.html"
to = "/iaed/cheatsheet/algoritmos"

[[redirects]]
from = "/iaed/meta/linux-setup.html"
to = "/iaed/meta/linux-setup"

[[redirects]]
from = "/iaed/algorimos-elementares-ordenacao"
to = "/iaed/algoritmos-elementares-ordenacao"

[[redirects]]
from = "/iaed/algorimos-eficientes-ordenacao"
to = "/iaed/algoritmos-eficientes-ordenacao"

[[redirects]]
from = "/iaed/algorimos-elementares-ordenacao-2"
to = "/iaed/algoritmos-elementares-ordenacao-2"

[[redirects]]
from = "/md"
to = "/emd"

[[redirects]]
from = "/md/perturbacoes"
to = "/emd/archive/perturbacoes"

[[redirects]]
from = "/md/introducao-calculo-finito"
to = "/emd/archive/introducao-calculo-finito"

[[redirects]]
from = "/md/formulas-fechadas-somatorios"
to = "/emd/archive/formulas-fechadas-somatorios"

[[redirects]]
from = "/md/serie-harmonica"
to = "/emd/archive/serie-harmonica"

[[redirects]]
from = "/md/inducao-matematica"
to = "/emd/inducao-matematica"

[[redirects]]
from = "/md/formula-de-abel"
to = "/emd/archive/formula-de-abel"

[[redirects]]
from = "/md/funcoes-geradoras"
to = "/emd/funcoes-geradoras"

[[redirects]]
from = "/md/teorema-de-newton"
to = "/emd/archive/teorema-de-newton"

[[redirects]]
from = "/md/calculo-combinatorio"
to = "/emd/archive/calculo-combinatorio"

[[redirects]]
from = "/md/equacoes-diferencas-finitas"
to = "/emd/equacoes-diferencas-finitas"

[[redirects]]
from = "/md/fft"
to = "/emd/fft"

[[redirects]]
from = "/md/mdc-eq-diofantinas"
to = "/emd/mdc-eq-diofantinas"

[[redirects]]
from = "/md/calendario"
to = "/emd/archive/calendario"

[[redirects]]
from = "/md/pascoa"
to = "/emd/archive/pascoa"

[[redirects]]
from = "/md/congruencias"
to = "/emd/congruencias"

[[redirects]]
from = "/md/teorema-chines-restos"
to = "/emd/teorema-chines-restos"

[[redirects]]
from = "/md/rsa"
to = "/emd/rsa"

[[redirects]]
from = "/md/grafos"
to = "/emd/grafos"

[[redirects]]
from = "/md/principio-pombal"
to = "/emd/principio-pombal"

[[redirects]]
from = "/md/labirintos"
to = "/emd/archive/labirintos"

[[redirects]]
from = "/md/relacionamentos-gale-shapley"
to = "/emd/archive/relacionamentos-gale-shapley"

[[redirects]]
from = "/md/kruskal-dijkstra"
to = "/emd/kruskal-dijkstra"

[[redirects]]
from = "/md/teoria-fluxo"
to = "/emd/archive/teoria-fluxo"

[[redirects]]
from = "/md/grafos-planares"
to = "/emd/archive/grafos-planares"

[[redirects]]
from = "/md/algoritmo-kuratowski"
to = "/emd/archive/algoritmo-kuratowski"

[[redirects]]
from = "/md/automatos-finitos"
to = "/emd/archive/automatos-finitos"

[[redirects]]
from = "/md/cheatsheet/calculo-finito"
to = "/emd/archive/cheatsheets/calculo-finito"

[[redirects]]
from = "/md/cheatsheet/funcoes-geradoras"
to = "/emd/archive/cheatsheets/funcoes-geradoras"

[[redirects]]
from = "/md/cheatsheet/calendarios"
to = "/emd/archive/cheatsheets/calendarios"

[[redirects]]
from = "/md/cheatsheet/mdc-equacoes-diofantinas"
to = "/emd/cheatsheets/mdc-equacoes-diofantinas"

[[redirects]]
from = "/md/cheatsheet/rsa"
to = "/emd/cheatsheets/rsa"

[[redirects]]
from = "/md/cheatsheet/grafos"
to = "/emd/cheatsheets/grafos"

[[redirects]]
from = "/md/exercicios/fichas-aulas-praticas"
to = "/emd/exercicios/fichas-2020-2021"

[[redirects]]
from = "/md/tools/fft-calculator"
to = "/emd/tools/fft-calculator"

[[redirects]]
from = "/md/tools/calendar-calculator"
to = "/emd/tools/calendar-calculator"

[[redirects]]
from = "/md/tools/mdc-bezout-calculator"
to = "/emd/tools/mdc-bezout-calculator"

[[redirects]]
from = "/md/tools/teorema-chines-restos-table-calculator"
to = "/emd/tools/teorema-chines-restos-table-calculator"

[[redirects]]
from = "/md/tools/rsa-calculator"
to = "/emd/tools/rsa-calculator"
